//! Per-rule evidence: fixture-driven verification of rule behavior.
//!
//! Every rule pack may carry annotated fixture files under
//! `rules/<lang>/tests/<rule-id>/`. Inside a fixture, line annotations declare
//! the expected findings for that rule:
//!
//! ```text
//! db.query("..." + req.query.id);  // crit:expect js.sql-injection
//! db.query("SELECT 1");            // crit:expect-not js.sql-injection
//! // crit:expect js.sql-injection     <- alone on a line: applies to the next line
//! db.query(sql + tainted);
//! ```
//!
//! The harness scans each rule's fixture directory with only that rule
//! enabled and checks the findings against the annotations, strictly: every
//! `expect` line must have a finding, every `expect-not` line must not, and
//! no finding may land on an unannotated line. Verified counts are recorded
//! in `rules/evidence.yaml` (regenerated by `crit rules verify
//! --write-evidence`), from which SARIF `precision` is derived — rules
//! without fixtures honestly report `low` precision.

use crate::config::Config;
use crate::languages::Registry;
use crate::rules::CompiledRuleSet;
use crate::scanner::{self, ScanOptions};
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::Path;
use std::sync::OnceLock;

/// File name of the generated evidence document inside a rules directory.
pub const EVIDENCE_FILE: &str = "evidence.yaml";
/// Directory name (inside a language pack) holding per-rule fixtures.
pub const TESTS_DIR: &str = "tests";

/// One line-level expectation parsed from a fixture file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Expectation {
    pub rule_id: String,
    /// 1-based line the expectation applies to.
    pub line: u32,
    /// true = a finding must land on this line; false = none may.
    pub expect: bool,
}

/// Parse `crit:expect` / `crit:expect-not` annotations from fixture source.
///
/// An annotation applies to its own line, unless the line contains nothing
/// but comment furniture besides the annotation, in which case it applies to
/// the following line.
pub fn parse_expectations(source: &str) -> Vec<Expectation> {
    static RE: OnceLock<regex::Regex> = OnceLock::new();
    let re = RE.get_or_init(|| {
        regex::Regex::new(r"crit:expect(-not)?[ \t]+([A-Za-z0-9_.:-]+)").expect("static regex")
    });

    let mut out = Vec::new();
    for (idx, line) in source.lines().enumerate() {
        let mut stripped = line.to_string();
        let mut anns: Vec<(bool, String)> = Vec::new();
        for cap in re.captures_iter(line) {
            anns.push((cap.get(1).is_none(), cap[2].to_string()));
            stripped = stripped.replace(&cap[0], "");
        }
        if anns.is_empty() {
            continue;
        }
        // Comment furniture across the supported comment syntaxes
        // (`//`, `#`, `;`, `{ }`, `(* *)`, `/* */`, `--`).
        let bare = stripped
            .chars()
            .filter(|c| !c.is_whitespace() && !"/#;*{}()-!'\"".contains(*c))
            .count();
        let target = if bare == 0 { idx + 2 } else { idx + 1 } as u32;
        for (expect, rule_id) in anns {
            out.push(Expectation {
                rule_id,
                line: target,
                expect,
            });
        }
    }
    out
}

/// Verified fixture counts for one rule, as persisted in `evidence.yaml`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct EvidenceEntry {
    /// Number of `expect` annotations that produced a finding.
    pub positives: u32,
    /// Number of `expect-not` annotations that stayed clean.
    pub negatives: u32,
}

/// The generated `rules/evidence.yaml` document.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct EvidenceFile {
    pub evidence: BTreeMap<String, EvidenceEntry>,
}

impl EvidenceFile {
    pub fn parse(text: &str) -> Result<Self> {
        serde_yaml::from_str(text).context("invalid evidence YAML")
    }

    pub fn to_yaml(&self) -> String {
        let body = serde_yaml::to_string(self).expect("evidence serializes");
        format!("# Generated by `crit rules verify --write-evidence`. Do not edit by hand.\n{body}")
    }
}

/// SARIF precision tier derived from verified fixture counts.
pub fn derive_precision(entry: &EvidenceEntry) -> &'static str {
    if entry.positives >= 2 && entry.negatives >= 2 {
        "high"
    } else if entry.positives >= 1 && entry.negatives >= 1 {
        "medium"
    } else {
        "low"
    }
}

/// Result of verifying one rule's fixture directory.
#[derive(Debug, Default)]
pub struct RuleReport {
    pub entry: EvidenceEntry,
    /// Human-readable mismatches; empty means the rule verified cleanly.
    pub failures: Vec<String>,
}

/// Full harness result over a rules directory.
#[derive(Debug, Default)]
pub struct EvidenceReport {
    pub per_rule: BTreeMap<String, RuleReport>,
}

impl EvidenceReport {
    pub fn is_ok(&self) -> bool {
        self.per_rule.values().all(|r| r.failures.is_empty())
    }

    pub fn failures(&self) -> impl Iterator<Item = (&str, &str)> {
        self.per_rule
            .iter()
            .flat_map(|(id, r)| r.failures.iter().map(move |f| (id.as_str(), f.as_str())))
    }

    /// The evidence document these results correspond to. Rules with any
    /// failure are excluded — evidence records verified behavior only.
    pub fn to_evidence_file(&self) -> EvidenceFile {
        EvidenceFile {
            evidence: self
                .per_rule
                .iter()
                .filter(|(_, r)| r.failures.is_empty())
                .map(|(id, r)| (id.clone(), r.entry))
                .collect(),
        }
    }
}

/// Run the evidence harness over every `<lang>/tests/<rule-id>/` fixture
/// directory under `rules_root`, using an already compiled rule set.
pub fn run(
    rules_root: &Path,
    registry: &Registry,
    ruleset: &CompiledRuleSet,
) -> Result<EvidenceReport> {
    let mut report = EvidenceReport::default();

    let mut rule_dirs: Vec<(String, std::path::PathBuf)> = Vec::new();
    for lang_entry in std::fs::read_dir(rules_root)
        .with_context(|| format!("failed to list rules root {}", rules_root.display()))?
    {
        let tests = lang_entry?.path().join(TESTS_DIR);
        if !tests.is_dir() {
            continue;
        }
        for rule_entry in std::fs::read_dir(&tests)? {
            let dir = rule_entry?.path();
            if dir.is_dir() {
                let rule_id = dir
                    .file_name()
                    .and_then(|n| n.to_str())
                    .unwrap_or_default()
                    .to_string();
                rule_dirs.push((rule_id, dir));
            }
        }
    }
    rule_dirs.sort();

    for (rule_id, dir) in rule_dirs {
        let rule_report = verify_rule(&rule_id, &dir, registry, ruleset)?;
        report.per_rule.insert(rule_id, rule_report);
    }
    Ok(report)
}

fn verify_rule(
    rule_id: &str,
    dir: &Path,
    registry: &Registry,
    ruleset: &CompiledRuleSet,
) -> Result<RuleReport> {
    let mut report = RuleReport::default();
    if !ruleset.rules.contains_key(rule_id) {
        report.failures.push(format!(
            "fixture directory exists but no rule `{rule_id}` is loaded"
        ));
        return Ok(report);
    }

    let opts = ScanOptions {
        rule_filter: vec![rule_id.to_string()],
        use_cache: false,
        ..Default::default()
    };
    let outcome = scanner::scan(dir, registry, ruleset, &Config::default(), &opts)?;
    for err in &outcome.errors {
        report.failures.push(format!("scan error: {err}"));
    }

    // (file, line) -> finding present. Findings' `file` is dir-relative.
    let mut found: BTreeMap<(String, u32), u32> = BTreeMap::new();
    for f in &outcome.findings {
        *found
            .entry((f.file.clone(), f.span.start.line))
            .or_insert(0) += 1;
    }

    // Parse expectations per fixture file (dir-relative forward-slash paths,
    // matching finding paths).
    let mut expected: BTreeMap<(String, u32), bool> = BTreeMap::new();
    let mut files = 0usize;
    for entry in walk_fixture_files(dir)? {
        files += 1;
        let rel = entry
            .strip_prefix(dir)
            .unwrap_or(&entry)
            .to_string_lossy()
            .replace(std::path::MAIN_SEPARATOR, "/");
        let source = std::fs::read_to_string(&entry)
            .with_context(|| format!("failed to read fixture {}", entry.display()))?;
        for exp in parse_expectations(&source) {
            if exp.rule_id != rule_id {
                report.failures.push(format!(
                    "{rel}:{}: annotation names `{}` but this directory tests `{rule_id}`",
                    exp.line, exp.rule_id
                ));
                continue;
            }
            expected.insert((rel.clone(), exp.line), exp.expect);
        }
    }
    if files == 0 {
        report.failures.push("fixture directory is empty".into());
        return Ok(report);
    }

    for ((file, line), expect) in &expected {
        let hit = found.contains_key(&(file.clone(), *line));
        match (expect, hit) {
            (true, true) => report.entry.positives += 1,
            (false, false) => report.entry.negatives += 1,
            (true, false) => report.failures.push(format!(
                "{file}:{line}: expected a `{rule_id}` finding, got none"
            )),
            (false, true) => report.failures.push(format!(
                "{file}:{line}: expected no `{rule_id}` finding, got one"
            )),
        }
    }
    // Strict: findings on unannotated lines are failures too.
    for (file, line) in found.keys() {
        if !expected.contains_key(&(file.clone(), *line)) {
            report.failures.push(format!(
                "{file}:{line}: unannotated `{rule_id}` finding (add crit:expect or fix the rule)"
            ));
        }
    }
    Ok(report)
}

fn walk_fixture_files(dir: &Path) -> Result<Vec<std::path::PathBuf>> {
    let mut out = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        for entry in
            std::fs::read_dir(&d).with_context(|| format!("failed to list {}", d.display()))?
        {
            let path = entry?.path();
            if path.is_dir() {
                stack.push(path);
            } else {
                out.push(path);
            }
        }
    }
    out.sort();
    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn annotations_on_own_line_apply_to_next() {
        let src = "// crit:expect js.x\ndb.query(a);\nexec(b); // crit:expect-not js.x\n";
        let exps = parse_expectations(src);
        assert_eq!(
            exps,
            vec![
                Expectation {
                    rule_id: "js.x".into(),
                    line: 2,
                    expect: true
                },
                Expectation {
                    rule_id: "js.x".into(),
                    line: 3,
                    expect: false
                },
            ]
        );
    }

    #[test]
    fn pascal_and_hash_comments_parse() {
        let src =
            "{ crit:expect pas.sql-injection }\nQ.SQL.Text := s;\nx := 1; # crit:expect-not os.x\n";
        let exps = parse_expectations(src);
        assert_eq!(exps[0].line, 2);
        assert!(exps[0].expect);
        assert_eq!(exps[1].line, 3);
        assert!(!exps[1].expect);
    }

    #[test]
    fn precision_tiers() {
        let e = |p, n| EvidenceEntry {
            positives: p,
            negatives: n,
        };
        assert_eq!(derive_precision(&e(2, 2)), "high");
        assert_eq!(derive_precision(&e(1, 1)), "medium");
        assert_eq!(derive_precision(&e(3, 0)), "low");
        assert_eq!(derive_precision(&e(0, 0)), "low");
    }
}
